# Generated by Django 2.2 on 2021-02-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category4',
        ),
    ]
