# Generated by Django 2.2 on 2021-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_auto_20210207_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Pet Care', 'Pet Care'), ('Electrical', 'Electrical'), ('Garden', 'Garden')], max_length=50, null=True),
        ),
    ]
