# Generated by Django 2.2 on 2021-02-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0004_auto_20210207_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('1', 'Pet Care'), ('2', 'Electrical'), ('3', 'Garden')], default=2, max_length=50, null=True),
        ),
    ]
